apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
      namespace: ${NAMESPACE}
      spec:
          replicas: 1
            selector:
                  matchLabels:
                          app: mysql
                            template:
                                  metadata:
                                          labels:
                                                    app: mysql
                                                        spec:
                                                                containers:
                                                                        - name: mysql
                                                                                image: ${MYSQL_IMAGE}
                                                                                        env:
                                                                                                  - name: MYSQL_ROOT_PASSWORD
                                                                                                            value: ${MYSQL_ROOT_PASSWORD}
                                                                                                                    ports:
                                                                                                                              - containerPort: 3306
                                                                                                                                      volumeMounts:
                                                                                                                                                - name: mysql-persistent-storage
                                                                                                                                                          mountPath: /var/lib/mysql
                                                                                                                                                                volumes:
                                                                                                                                                                        - name: mysql-persistent-storage
                                                                                                                                                                                persistentVolumeClaim:
                                                                                                                                                                                            claimName: mysql-pv-claim
                                                                                                                                                                                                  imagePullSecrets:
                                                                                                                                                                                                          - name: dockerhub-secret  # Add this line if your DockerHub repository is private

