apiVersion: v1
kind: Service
metadata:
    name: voting-app
      namespace: ${NAMESPACE}
      spec:
          type: LoadBalancer
            ports:
                - port: 80
                    targetPort: 80
                      selector:
                            app: voting-app

